apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-reviewer-backend-deployment
  labels:
    app: code-reviewer-backend
  namespace: code-reviewer-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: code-reviewer-backend
  template:
    metadata:
      labels:
        app: code-reviewer-backend
    spec:
      containers:
      - name: code-reviewer-backend
        image: aahhhkash/code-reviewer-backend:backend-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
