apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeReviewer-backend-deployment
  labels:
    app: codeReviewer-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: codeReviewer-backend
  template:
    metadata:
      labels:
        app: codeReviewer-backend
    spec:
      containers:
      - name: codeReviewer-backend
        image: codeReviewer-backend:latest
        ports:
        - containerPort: 3000
