apiVersion: v1
kind: Service
metadata:
  name: code-reviewer-backend-service
  namespace: code-reviewer-namespace
spec:
  selector:
    app: code-reviewer-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000