apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: code-reviewer-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: code-reviewer-backend
            port:
              number: 3000
