apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-reviewer-frontend-deployment
  labels:
    app: code-reviewer-frontend
  namespace: code-reviewer-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: code-reviewer-frontend
  template:
    metadata:
      labels:
        app: code-reviewer-frontend
    spec:
      containers:
      - name: code-reviewer-frontend
        image: aahhhkash/code-reviewer-frontend:frontend-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
