apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeReviewer-frontend-deployment
  labels:
    app: codeReviewer-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: codeReviewer-frontend
  template:
    metadata:
      labels:
        app: codeReviewer-frontend
    spec:
      containers:
      - name: codeReviewer-frontend
        image: codeReviewer-frontend:latest
        ports:
        - containerPort: 5173
