apiVersion: v1
kind: Service
metadata:
  name: code-reviewer-frontend-service
  namespace: code-reviewer-namespace
spec:
  selector:
    app: code-reviewer-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80